export enum ExpenseCategory {
  MAINTENANCE = 'MAINTENANCE',
  UTILITY = 'UTILITY',
  INSURANCE = 'INSURANCE',
  GOV_FEE = 'GOV_FEE',
  MUNICIPALITY_FEE = 'MUNICIPALITY_FEE',
  CLEANING = 'CLEANING',
  SECURITY = 'SECURITY',
  MANAGEMENT = 'MANAGEMENT',
  LEGAL = 'LEGAL',
  SALARY = 'SALARY',
  OTHER = 'OTHER',
}
